from NN import learning_params,data_preprocess,wandb_run_configuration
import argparse
parser = argparse.ArgumentParser(description='Run my model function')
parser.add_argument('-wp','--wandb_project', default="CS6910_Assignment-1", required=False,metavar="", type=str, help=' ')
parser.add_argument('-we','--wandb_entity', default="cs22m078", required=False,metavar="", type=str, help='')
parser.add_argument('-d','--dataset', default="fashion_mnist", required=False,metavar="", type=str,choices= ["mnist", "fashion_mnist"], help=' ')
parser.add_argument('-e','--epochs', default=10, required=False,metavar="", type=int, help=' ')
parser.add_argument('-b','--batch_size', default=32, required=False,metavar="", type=int, help=' ')
parser.add_argument('-o','--optimizer', default="nadam", required=False,metavar="", type=str,choices= ["sgd", "momentum", "nag", "rmsprop", "adam", "nadam"], help=' ')
parser.add_argument('-l','--loss', default="cross_entropy", required=False,metavar="", type=str,choices= ["mean_squared_error", "cross_entropy"], help=' ')
parser.add_argument('-lr','--learning_rate', default=0.001, required=False,metavar="", type=int, help='')
parser.add_argument('-m','--momentum', default=0.9, required=False,metavar="", type=int, help=' ')
parser.add_argument('-beta','--beta', default=0.9, required=False,metavar="", type=int, help=' ')
parser.add_argument('-beta1','--beta1', default=0.9, required=False,metavar="", type=int, help=' ')
parser.add_argument('-beta2','--beta2', default=0.99, required=False,metavar="", type=int, help=' ')
parser.add_argument('-eps','--epsilon', default=0.00001, required=False,metavar="", type=int, help=' ')
parser.add_argument('-w_d','--weight_decay', default=.0, required=False,metavar="", type=int, help=' ')
parser.add_argument('-w_i','--weight_init', default="xavier", required=False,metavar="", type=str,choices= ["random", "xavier"], help=' ')
parser.add_argument('-nhl','--num_layers', default=6, required=False,metavar="", type=int, help=' ')
parser.add_argument('-sz','--hidden_size', default=64, required=False,metavar="", type=int, help=' ')
parser.add_argument('-a','--activation', default="ReLU", required=False,metavar="", type=str,choices= ["identity", "sigmoid", "tanh", "ReLU"], help=' ')
args = parser.parse_args()
_,_,train_x,train_y,val_x,val_y,x_test,y_test=data_preprocess(args.dataset)
wandb_run_configuration(args.wandb_project,args.wandb_entity,args.num_layers,args.hidden_size,train_x,train_y,val_x,val_y,x_test,y_test,args.optimizer,args.learning_rate,args.epochs,args.batch_size,args.activation,args.weight_init,args.weight_decay,args.momentum ,args.beta ,args.beta1 ,args.beta2 ,args.epsilon,args.loss)
