from NN import learning_params,train_x,train_y,val_x,val_y
import argparse
parser = argparse.ArgumentParser(description='Run my model function')
parser.add_argument('-wp','--wandb_project', default="CS6910_Assignment-1", required=False,metavar="", type=str, help=' ')
parser.add_argument('-we','--wandb_entity', default="Sarthak Naithani", required=False,metavar="", type=str, help='')
parser.add_argument('-d','--dataset', default="fashion_mnist", required=False,metavar="", type=str,choices= ["mnist", "fashion_mnist"], help=' ')
parser.add_argument('-e','--epochs', default=10, required=False,metavar="", type=int, help=' ')
parser.add_argument('-b','--batch_size', default=32, required=False,metavar="", type=int, help=' ')
parser.add_argument('-o','--optimizer', default="adam", required=False,metavar="", type=str,choices= ["sgd", "momentum", "nag", "rmsprop", "adam", "nadam"], help=' ')
parser.add_argument('-l','--loss', default="cross_entropy", required=False,metavar="", type=str,choices= ["mean_squared_error", "cross_entropy"], help=' ')
parser.add_argument('-lr','--learning_rate', default=0.01, required=False,metavar="", type=int, help='')
parser.add_argument('-m','--momemtum', default=0.9, required=False,metavar="", type=int, help=' ')
parser.add_argument('-beta','--beta', default=0.9, required=False,metavar="", type=int, help=' ')
parser.add_argument('-beta1','--beta1', default=0.9, required=False,metavar="", type=int, help=' ')
parser.add_argument('-beta2','--beta2', default=0.99, required=False,metavar="", type=int, help=' ')
parser.add_argument('-eps','--epsilon', default=0.00001, required=False,metavar="", type=int, help=' ')
parser.add_argument('-w_d','--weight_decay', default=.0, required=False,metavar="", type=int, help=' ')
parser.add_argument('-w_i','--weight_init', default="random", required=False,metavar="", type=str,choices= ["random", "Xavier"], help=' ')
parser.add_argument('-nhl','--num_layers', default=3, required=False,metavar="", type=int, help=' ')
parser.add_argument('-sz','--hidden_size', default=32, required=False,metavar="", type=int, help=' ')
parser.add_argument('-a','--activation', default="sigmoid", required=False,metavar="", type=str,choices= ["identity", "sigmoid", "tanh", "ReLU"], help=' ')
args = parser.parse_args()
weights,biases,epoch_train_loss,epoch_val_loss,acc_train,acc_val=learning_params(args.num_layers,args.hidden_size,train_x,train_y,val_x,val_y,args.optimizer,args.learning_rate,args.epochs,args.batch_size,args.activation,args.weight_init,args.weight_decay,args.momemtum ,args.beta ,args.beta1 ,args.beta2 ,args.epsilon)
print(acc_val[-1])